name: unit4_assignment_alanan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: ComicSansMS
      fonts:
        - asset: fonts/COMIC.ttf
  assets:
    - assets/images/Profile.jpg
  uses-material-design: true
